GET http://127.0.0.1:3000/playlists


###
GET http://127.0.0.1:3000/playlists/1fnuSGnTALt3nEQkLjOPq8
Content-Type: application/json

###
POST http://127.0.0.1:3000/playlists
Content-Type: application/json

