
### SharedPlaylists Index
GET http://localhost:3000/shared_playlists

###
POST http://localhost:3000/shared_playlists
Content-Type: application/json

{
  "playlist_id": "SDFKJEIJSDLKFJ839",
  "user_id": "2"
}

### SharedPlaylists show
GET http://localhost:3000/shared_playlists/3

### SharedPlaylists update
PATCH http://localhost:3000/shared_playlists/2
Content-Type: application/json

{
  "user_id": 1
}

###
DELETE http://localhost:3000/shared_playlists/2