###
GET http://127.0.0.1:3000/api/spotify/callback
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU4MTk4ODl9.2ZxwjCtVLwLF_R87GsYcF-n-neTvGp2QvQBAAciHHls


###
GET http://127.0.0.1:3000/api/spotify/top_songs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUzNzU2MTJ9.tTxwHfnC1aUV9zfCTlTwpagXSHUxzMFKFA41auIKIhI

###
GET https://api.spotify.com/v1/me/top/tracks?time_range=medium_term&limit=200&offset=5
Authorization: Bearer BQDFryYVZhKnf-053Id3yVPsFxyhnCciK-yBljzGMiWbxiU5wom6mqvVSJWq6ItFYjUW_-iSQ0FQGm1dYvsJrypy5hL9ZhSodd9945kwREfh8g4ik5mXJQjq4nDD64sGKNwlJbEpwIvcpuhiYhxhP_9o0mg1FO1pD_YX9NK8q-12DDiK
Content-Type: application/json


