@jwt = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU4MTk4ODl9.2ZxwjCtVLwLF_R87GsYcF-n-neTvGp2QvQBAAciHHls"
###
POST http://127.0.0.1:3000/users
Content-Type: application/json

{
  "name": "robert",
  "email": "robert@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "jack@gmail.com",
  "password": "password"
}
###

### Users show
GET http://localhost:3000/users/1

### Update user
PATCH http://localhost:3000/users/
Content-Type: application/json

{
  "name": "Jon",
  "password": "password",
  "password_confirmation": "password"
  
}

### Destroy user
DELETE http://localhost:3000/users/3
